default_stages: [commit]

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - venv-run
        entry: venv-run mypy .
        types: [python]
        pass_filenames: false
        require_serial: true
