[tool.ruff]
target-version = "py37"
select = ["E", "F", "I"]
ignore = [
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
  "E501",
]
src = ["src", "tests"]

[tool.mypy]
python_version = "3.7"
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
enable_error_code = "ignore-without-code,redundant-self,truthy-iterable"
strict = true
warn_unreachable = true
exclude = "^build/"
