[tool.ruff]
target-version = "py37"
select = ["E", "F", "I"]
src = ["src", "tests"]

[tool.mypy]
python_version = "3.7"
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
enable_error_code = "ignore-without-code,redundant-self,truthy-iterable"
strict = true
warn_unreachable = true
exclude = "^build/"
